### ISSUE TITLE
[User Settings] [Backend] Update portfolio defaults

### ISSUE THREAD

**Issue by susansli** [susansli/augury#46]
## Story
As a user, I want to make updates to my portfolio defaults when my preferences change.

## Specifications
Create an endpoint that takes an updated default portfolio object and updates the entry for the particular user/

## Acceptance
- [ ] Endpoints created and proper interfaces/documentation passed to the frontend team

**Comment by LukarioMC** [comment]
Impl in: #84 

**Endpoint:**
PUT `{{server_url}}/user/portfolio/defaults`

**Interface:**
```
{
  userId: Types.ObjectId | string;
  name: string; // Portfolio name
  risk?: PortfolioRisk; // Optional risk if `useCustomRisk` is true
  useCustomRisk: boolean; // If true, indicates custom risk settings are used
  customRiskPercentage1?: number; // First custom percentage value if using custom risk
  customRiskPercentage2?: number; // Second custom percentage value if using custom risk
  sectorTags?: Sectors[]; // Array of sector tags
}
```
