### ISSUE TITLE
[User Settings] [Backend] Update account balance

### ISSUE THREAD

**Issue by susansli** [susansli/augury#47]
## Story
As a user, I want to make updates to my account balance when I want to increase or decrease the money I hold.

## Specifications
Create an endpoint that takes a float and adds it to the amount existing in the account. This float can be negative. Account balance should never dip below zero.

## Acceptance
- [x] Endpoints created and proper interfaces/documentation passed to the frontend team
- [x] Endpoint successfully refreshes the account balance for the current user when it is called

**Comment by crystal-g77** [comment]
To use send a PUT request to /User/Balance with a query including the new balance
"/User/Balance?balance=${balance}"

**Comment by LukarioMC** [comment]
Endpoint constraints were a slightly unclear as this seemed contradictory: 
>This float can be negative. Account balance should never dip below zero.
so we had implemented it without extra validation whether they are adding/removing balance.

If this had meant that we should only be able to take money out of the account if their account is in the positive, then the check is trivial to add into the handler function. 👍
