### ISSUE TITLE
[User Account] [Backend] Get a user

### ISSUE THREAD

**Issue by susansli** [susansli/augury#48]
## Story
As a system, we need to be able to fetch a user that is associated with an account.

## Specifications
The flow should go something like:
- The frontend needs to send a request to the backend to validate the current session (if it exists)
- The backend needs to send a response with the correct User object
And endpoint needs to be created that does this.

## Acceptance
- [x] Endpoint created and proper interfaces/documentation passed to the frontend team
- [x] Endpoint successfully validates the existing session and returns the correct user object when it is called

**Comment by crystal-g77** [comment]
Get request to
/User

**Comment by LukarioMC** [comment]
May need to review if we should be hiding certain parts of user data or if just mapping it to the response is alright (e.g. should we hide the `_id` field in response?)
