### ISSUE TITLE
[User Account] [Backend] Create unified API for updating the user's portfolio defaults and account balance

### ISSUE THREAD

**Issue by susansli** [susansli/augury#65]
## Story
As a system, I should only be making **one** HTTP request to update the user's information after I add portfolio defaults and initial account balance.

## Pre-requisites
- #66 
The FE team must give the BE devs the proper interface of the request body

## Acceptance
- [x] API route created that receives the interface of the update and applies those values to the User's records
- [x] Proper endpoint and request body parameters given to the FE team

**Comment by LukarioMC** [comment]
Impl in: #84 

**Endpoint:**
POST `{{server_url}}/user/onboard`

**Interface:**

Interfaces for client onboarding request & response
```ts
interface OnboardingRequestBody {
  id: string;
  balance: number;
  defaults: Portfolio;
}

interface OnboardingResponse {
  user: User;
  defaults: PortfolioDefault;
}
```
These are the current defs for each custom type above:
```ts
export default interface Portfolio extends Identifiable {
  name: string; // Portfolio name
  risk?: PortfolioRisk; // Optional risk if `useCustomRisk` is true
  useCustomRisk: boolean; // If true, indicates custom risk settings are used
  customRiskPercentage1?: number; // First custom percentage value if using custom risk
  customRiskPercentage2?: number; // Second custom percentage value if using custom risk
  sectorTags?: Sectors[]; // Array of sector tags
}

export default interface PortfolioDefault extends Portfolio {
  userId: Types.ObjectId | string;
}
```
