### ISSUE TITLE
[Assignment] HLD diagrams

### ISSUE THREAD

**Issue by susansli** [susansli/augury#83]
Create the HLD diagrams we need to complete submissions for the Sprint 2 deliverables.

**Comment by susansli** [comment]
I put @LukarioMC and @crystal-g77 on this since they've been building the logical parts of the backend and would be more acquainted with the entities, sequences, and so on.

**Comment by LukarioMC** [comment]
**Link to HLD**: https://github.com/Fall2024-comp7082/sprint-ii-planning-and-high-level-design-document-ai-finance-bros-1
